/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eventticketregistrationsystem;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class TicketForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TicketForm.class.getName());

    
    // Creates new form TicketForm
    public TicketForm() {
        initComponents();
        
        // Default ticket type
        cmbTicketType.setSelectedIndex(0);

        // Early Bird is selected by default
        txtHowEarly.setEnabled(true);

        // VIP fields are disabled
        txtBackstagePassFee.setEnabled(false);
        chkParking.setEnabled(false);

        // Default final price
        lblFinalPrice.setText("Final Price: RM 0.00");

        // Put form in the center of the screen
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTicketRegistration = new javax.swing.JLabel();
        lblTikcketID = new javax.swing.JLabel();
        txtTicketID = new javax.swing.JTextField();
        lblEventName = new javax.swing.JLabel();
        txtEventName = new javax.swing.JTextField();
        lblAttendeeName = new javax.swing.JLabel();
        txtAttendeeName = new javax.swing.JTextField();
        lblBasePrice = new javax.swing.JLabel();
        txtBasePrice = new javax.swing.JTextField();
        lblTicketType = new javax.swing.JLabel();
        cmbTicketType = new javax.swing.JComboBox<>();
        lblHowEarly = new javax.swing.JLabel();
        txtHowEarly = new javax.swing.JTextField();
        lblBackstagePassFee = new javax.swing.JLabel();
        txtBackstagePassFee = new javax.swing.JTextField();
        chkParking = new javax.swing.JCheckBox();
        btnCalculate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblFinalPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTicketRegistration.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTicketRegistration.setText("TICKET REGISTRATION");

        lblTikcketID.setText("Ticket ID: ");

        txtTicketID.addActionListener(this::txtTicketIDActionPerformed);

        lblEventName.setText("Event Name: ");

        txtEventName.addActionListener(this::txtEventNameActionPerformed);

        lblAttendeeName.setText("Attendee Name:");

        txtAttendeeName.addActionListener(this::txtAttendeeNameActionPerformed);

        lblBasePrice.setText("Base Price: ");

        txtBasePrice.addActionListener(this::txtBasePriceActionPerformed);

        lblTicketType.setText("Ticket Type:");

        cmbTicketType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Early Bird", "VIP" }));
        cmbTicketType.addActionListener(this::cmbTicketTypeActionPerformed);

        lblHowEarly.setText("How Early:  ");

        txtHowEarly.addActionListener(this::txtHowEarlyActionPerformed);

        lblBackstagePassFee.setText("Backstage Pass Fee: ");

        txtBackstagePassFee.addActionListener(this::txtBackstagePassFeeActionPerformed);

        chkParking.setText("Parking Access");

        btnCalculate.setBackground(new java.awt.Color(153, 204, 255));
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(this::btnCalculateActionPerformed);

        btnReset.setBackground(new java.awt.Color(255, 204, 153));
        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        lblFinalPrice.setText("Final Price: RM 0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTikcketID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTicketID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEventName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEventName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAttendeeName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAttendeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBasePrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTicketType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbTicketType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHowEarly)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHowEarly, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkParking)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBackstagePassFee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBackstagePassFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFinalPrice))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTicketRegistration)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnCalculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReset)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTicketRegistration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTikcketID)
                    .addComponent(txtTicketID, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEventName)
                    .addComponent(txtEventName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAttendeeName)
                    .addComponent(txtAttendeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBasePrice)
                    .addComponent(txtBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTicketType)
                    .addComponent(cmbTicketType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHowEarly)
                    .addComponent(txtHowEarly, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBackstagePassFee)
                    .addComponent(txtBackstagePassFee, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chkParking)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculate)
                    .addComponent(btnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFinalPrice)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTicketIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTicketIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTicketIDActionPerformed

    private void txtEventNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEventNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEventNameActionPerformed

    private void txtAttendeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAttendeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAttendeeNameActionPerformed

    private void txtBasePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBasePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBasePriceActionPerformed

    private void cmbTicketTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTicketTypeActionPerformed
        String ticketType = cmbTicketType.getSelectedItem().toString();

        if (ticketType.equals("Early Bird")) {

            // Enable Early Bird field
            txtHowEarly.setEnabled(true);

            // Disable VIP fields
            txtBackstagePassFee.setEnabled(false);
            chkParking.setEnabled(false);

            // Clear VIP fields
            txtBackstagePassFee.setText("");
            chkParking.setSelected(false);

        } else {
           
            // Disable Early Bird field
            txtHowEarly.setEnabled(false);

            // Enable VIP fields
            txtBackstagePassFee.setEnabled(true);
            chkParking.setEnabled(true);

            // Clear Early Bird field
            txtHowEarly.setText(""); 
        }
    }//GEN-LAST:event_cmbTicketTypeActionPerformed

    private void txtHowEarlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHowEarlyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHowEarlyActionPerformed

    private void txtBackstagePassFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBackstagePassFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBackstagePassFeeActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TicketForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox chkParking;
    private javax.swing.JComboBox<String> cmbTicketType;
    private javax.swing.JLabel lblAttendeeName;
    private javax.swing.JLabel lblBackstagePassFee;
    private javax.swing.JLabel lblBasePrice;
    private javax.swing.JLabel lblEventName;
    private javax.swing.JLabel lblFinalPrice;
    private javax.swing.JLabel lblHowEarly;
    private javax.swing.JLabel lblTicketRegistration;
    private javax.swing.JLabel lblTicketType;
    private javax.swing.JLabel lblTikcketID;
    private javax.swing.JTextField txtAttendeeName;
    private javax.swing.JTextField txtBackstagePassFee;
    private javax.swing.JTextField txtBasePrice;
    private javax.swing.JTextField txtEventName;
    private javax.swing.JTextField txtHowEarly;
    private javax.swing.JTextField txtTicketID;
    // End of variables declaration//GEN-END:variables
}
