/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eventticketregistrationsystem;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class TicketForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TicketForm.class.getName());
    private String loggedinusername;
    
    // Creates new form TicketForm
    public TicketForm(String username) {
        initComponents();
        loggedinusername = username;
        // Default ticket type
        cmbTicketType.setSelectedIndex(0);

        // Early Bird is selected by default
        txtHowEarly.setEnabled(true);

        // VIP fields are disabled
        txtBackstagePassFee.setEnabled(false);
        chkParking.setEnabled(false);

        // Default final price
        lblFinalPrice.setText("Final Price: RM 0.00");
        
        loadtickettable();

        // Put form in the center of the screen
        setLocationRelativeTo(null);
    }
    private void loadtickettable() {
    DefaultTableModel tableModel = (DefaultTableModel) tblTicketList.getModel();
    tableModel.setRowCount(0);

    String sqlCommand = "SELECT * FROM ticket ORDER BY ticketId";
    try (Connection connect = DatabaseConnection.connect();
         PreparedStatement pst = connect.prepareStatement(sqlCommand);
         ResultSet rs = pst.executeQuery()) {

        while (rs.next()) {
            String ticketid = String.valueOf(rs.getInt("ticketId"));
            int ticketType = rs.getInt("ticketType");
            Ticket ticket;
            String typeLabel = (ticketType == 0) ? "Early Bird" : "VIP";

            if (ticketType == 0) {
                ticket = new earlyBirdTicket(ticketid, rs.getString("eventName"), rs.getString("attendeeName"), 
                                              rs.getDouble("basePrice"), rs.getInt("howEarly"));
            } else {
                ticket = new VIPTicket(ticketid, rs.getString("eventName"), rs.getString("attendeeName"), 
                                       rs.getDouble("basePrice"), rs.getDouble("backstagePassFee"), rs.getInt("parkingAccess") == 1);
            }

            tableModel.addRow(new Object[]{
                ticket.getTicketId(), ticket.getEventName(), ticket.getAttendeeName(),
                ticket.getBasePrice(), typeLabel, String.format("RM %.2f", ticket.calculateFinalPrice())
            });  
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Failed to load records:\n" + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
}
    private int getStaffId(Connection conn, String username) throws SQLException {
        String sql = "SELECT staffId FROM staff WHERE username = ?";
        try (PreparedStatement pst = conn.prepareStatement(sql)) {
            pst.setString(1, username);
            try (ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt("staffId");
                }
            }
        }
        return 1; // Fallback default ID if not found
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTicketRegistration = new javax.swing.JLabel();
        lblTikcketID = new javax.swing.JLabel();
        txtTicketID = new javax.swing.JTextField();
        lblEventName = new javax.swing.JLabel();
        txtEventName = new javax.swing.JTextField();
        lblAttendeeName = new javax.swing.JLabel();
        txtAttendeeName = new javax.swing.JTextField();
        lblBasePrice = new javax.swing.JLabel();
        txtBasePrice = new javax.swing.JTextField();
        lblTicketType = new javax.swing.JLabel();
        cmbTicketType = new javax.swing.JComboBox<>();
        lblHowEarly = new javax.swing.JLabel();
        txtHowEarly = new javax.swing.JTextField();
        lblBackstagePassFee = new javax.swing.JLabel();
        txtBackstagePassFee = new javax.swing.JTextField();
        chkParking = new javax.swing.JCheckBox();
        btnCalculate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblFinalPrice = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTicketList = new javax.swing.JTable();
        lblHowEarly1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTicketRegistration.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTicketRegistration.setText("TICKET REGISTRATION");

        lblTikcketID.setText("Ticket ID: ");

        txtTicketID.addActionListener(this::txtTicketIDActionPerformed);

        lblEventName.setText("Event Name: ");

        txtEventName.addActionListener(this::txtEventNameActionPerformed);

        lblAttendeeName.setText("Attendee Name: ");

        txtAttendeeName.addActionListener(this::txtAttendeeNameActionPerformed);

        lblBasePrice.setText("Base Price: ");

        txtBasePrice.addActionListener(this::txtBasePriceActionPerformed);

        lblTicketType.setText("Ticket Type:");

        cmbTicketType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Early Bird", "VIP" }));
        cmbTicketType.addActionListener(this::cmbTicketTypeActionPerformed);

        lblHowEarly.setText("Ticket bought: ");

        txtHowEarly.addActionListener(this::txtHowEarlyActionPerformed);

        lblBackstagePassFee.setText("Backstage Pass Fee: RM");

        txtBackstagePassFee.addActionListener(this::txtBackstagePassFeeActionPerformed);

        chkParking.setText("Parking Access");

        btnCalculate.setBackground(new java.awt.Color(153, 204, 255));
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(this::btnCalculateActionPerformed);

        btnReset.setBackground(new java.awt.Color(255, 204, 153));
        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        lblFinalPrice.setText("Final Price: RM 0.00");

        tblTicketList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "TicketID", "Event Name", "Attendee Name", "Base Price", "Ticket Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblTicketList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTicketListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTicketList);

        lblHowEarly1.setText("day(s) before event");

        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblBasePrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblEventName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEventName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblTicketType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbTicketType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblHowEarly)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHowEarly, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHowEarly1))
                    .addComponent(chkParking, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblBackstagePassFee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBackstagePassFee, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFinalPrice, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblAttendeeName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAttendeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnCalculate)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblTicketRegistration)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTikcketID)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTicketID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTicketRegistration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTikcketID)
                    .addComponent(txtTicketID, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEventName)
                    .addComponent(txtEventName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAttendeeName)
                    .addComponent(txtAttendeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBasePrice)
                    .addComponent(txtBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTicketType)
                    .addComponent(cmbTicketType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHowEarly)
                    .addComponent(txtHowEarly, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHowEarly1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBackstagePassFee, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBackstagePassFee))
                .addGap(18, 18, 18)
                .addComponent(chkParking)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculate)
                    .addComponent(btnReset)
                    .addComponent(btnSave)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFinalPrice)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTicketIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTicketIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTicketIDActionPerformed

    private void txtEventNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEventNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEventNameActionPerformed

    private void txtAttendeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAttendeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAttendeeNameActionPerformed

    private void txtBasePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBasePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBasePriceActionPerformed

    private void cmbTicketTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTicketTypeActionPerformed
        boolean isEarlyBird = cmbTicketType.getSelectedIndex() == 0;

        // Enable/Disable fields based on Ticket Type selection
        txtHowEarly.setEnabled(isEarlyBird);
        txtBackstagePassFee.setEnabled(!isEarlyBird);
        chkParking.setEnabled(!isEarlyBird);

        if (isEarlyBird) {
            txtBackstagePassFee.setText("");
            chkParking.setSelected(false);
        } else {
            txtHowEarly.setText("");
        }
    }//GEN-LAST:event_cmbTicketTypeActionPerformed

    private void txtHowEarlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHowEarlyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHowEarlyActionPerformed

    private void txtBackstagePassFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBackstagePassFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBackstagePassFeeActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        try {
            String id = txtTicketID.getText().trim();
            String event = txtEventName.getText().trim();
            String attendee = txtAttendeeName.getText().trim();
            double price = Double.parseDouble(txtBasePrice.getText().trim());

            Ticket ticket;
            if (cmbTicketType.getSelectedIndex() == 0) { // Early Bird
                int howEarly = Integer.parseInt(txtHowEarly.getText().trim());
                ticket = new earlyBirdTicket(id, event, attendee, price, howEarly);
            } else { // VIP
                double fee = Double.parseDouble(txtBackstagePassFee.getText().trim());
                boolean parking = chkParking.isSelected();
                ticket = new VIPTicket(id, event, attendee, price, fee, parking);
            }

            lblFinalPrice.setText(String.format("Final Price: RM %.2f", ticket.calculateFinalPrice()));
        } catch (NumberFormatException e) {
            lblFinalPrice.setText("Final Price: RM 0.00");
            if (evt != null) {
                JOptionPane.showMessageDialog(this, "Please fill in all ticket details with valid numerical values before calculating.", "Input Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtTicketID.setText("");
        txtTicketID.setEnabled(true); // Re-enable for creating new entries
        txtEventName.setText("");
        txtAttendeeName.setText("");
        txtBasePrice.setText("");
        txtHowEarly.setText("");
        txtBackstagePassFee.setText("");
        chkParking.setSelected(false);
        cmbTicketType.setSelectedIndex(0);
        cmbTicketTypeActionPerformed(null);
        lblFinalPrice.setText("Final Price: RM 0.00");
        tblTicketList.clearSelection();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblTicketListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTicketListMouseClicked
        int selectedRow = tblTicketList.getSelectedRow();
        if (selectedRow == -1) return;

        String ticketIdStr = tblTicketList.getValueAt(selectedRow, 0).toString();
        int ticketId = Integer.parseInt(ticketIdStr);

        String sql = "SELECT * FROM ticket WHERE ticketId = ?";
        try (Connection conn = DatabaseConnection.connect();
             PreparedStatement pst = conn.prepareStatement(sql)) {

            pst.setInt(1, ticketId);
            try (ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    txtTicketID.setText(String.valueOf(rs.getInt("ticketId")));
                    txtTicketID.setEnabled(false); // Gray out/disable Ticket ID when editing existing record

                    txtEventName.setText(rs.getString("eventName"));
                    txtAttendeeName.setText(rs.getString("attendeeName"));
                    txtBasePrice.setText(String.valueOf(rs.getDouble("basePrice")));

                    int type = rs.getInt("ticketType");
                    if (type == 0) { // Early Bird
                        cmbTicketType.setSelectedIndex(0);
                        txtHowEarly.setText(String.valueOf(rs.getInt("howEarly")));
                        txtBackstagePassFee.setText("");
                        chkParking.setSelected(false);
                    } else { // VIP
                        cmbTicketType.setSelectedIndex(1);
                        txtHowEarly.setText("");
                        txtBackstagePassFee.setText(String.valueOf(rs.getDouble("backstagePassFee")));
                        chkParking.setSelected(rs.getInt("parkingAccess") == 1);
                    }

                    // Perform price calculation display
                    btnCalculateActionPerformed(null);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error retrieving record details:\n" + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tblTicketListMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            // Validation check
            if (txtTicketID.getText().trim().isEmpty() ||
                txtEventName.getText().trim().isEmpty() ||
                txtAttendeeName.getText().trim().isEmpty() ||
                txtBasePrice.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill in all primary ticket fields.", "Validation Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int ticketId = Integer.parseInt(txtTicketID.getText().trim());
            String eventName = txtEventName.getText().trim();
            String attendeeName = txtAttendeeName.getText().trim();
            double basePrice = Double.parseDouble(txtBasePrice.getText().trim());
            int ticketType = cmbTicketType.getSelectedIndex(); // 0 = Early Bird, 1 = VIP

            Integer howEarly = null;
            Double backstagePassFee = null;
            Integer parkingAccess = null;

            if (ticketType == 0) {
                if (txtHowEarly.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please enter days bought in advance for Early Bird ticket.", "Validation Warning", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                howEarly = Integer.parseInt(txtHowEarly.getText().trim());
            } else {
                if (txtBackstagePassFee.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please enter backstage pass fee for VIP ticket.", "Validation Warning", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                backstagePassFee = Double.parseDouble(txtBackstagePassFee.getText().trim());
                parkingAccess = chkParking.isSelected() ? 1 : 0;
            }

            try (Connection conn = DatabaseConnection.connect()) {
                int staffId = getStaffId(conn, loggedinusername);

                if (txtTicketID.isEnabled()) {
                    // CREATE: Insert new record
                    String sqlInsert = """
                        INSERT INTO ticket (ticketId, eventName, attendeeName, basePrice, ticketType, howEarly, backstagePassFee, parkingAccess, whoCreated)
                        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """;
                    try (PreparedStatement pst = conn.prepareStatement(sqlInsert)) {
                        pst.setInt(1, ticketId);
                        pst.setString(2, eventName);
                        pst.setString(3, attendeeName);
                        pst.setDouble(4, basePrice);
                        pst.setInt(5, ticketType);
                        if (howEarly != null) pst.setInt(6, howEarly); else pst.setNull(6, Types.INTEGER);
                        if (backstagePassFee != null) pst.setDouble(7, backstagePassFee); else pst.setNull(7, Types.REAL);
                        if (parkingAccess != null) pst.setInt(8, parkingAccess); else pst.setNull(8, Types.INTEGER);
                        pst.setInt(9, staffId);

                        pst.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Ticket registered successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    // UPDATE: Modify existing record
                    String sqlUpdate = """
                        UPDATE ticket 
                        SET eventName = ?, attendeeName = ?, basePrice = ?, ticketType = ?, howEarly = ?, backstagePassFee = ?, parkingAccess = ?, whoCreated = ?
                        WHERE ticketId = ?
                    """;
                    try (PreparedStatement pst = conn.prepareStatement(sqlUpdate)) {
                        pst.setString(1, eventName);
                        pst.setString(2, attendeeName);
                        pst.setDouble(3, basePrice);
                        pst.setInt(4, ticketType);
                        if (howEarly != null) pst.setInt(5, howEarly); else pst.setNull(5, Types.INTEGER);
                        if (backstagePassFee != null) pst.setDouble(6, backstagePassFee); else pst.setNull(6, Types.REAL);
                        if (parkingAccess != null) pst.setInt(7, parkingAccess); else pst.setNull(7, Types.INTEGER);
                        pst.setInt(8, staffId);
                        pst.setInt(9, ticketId);

                        pst.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Ticket record updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }

            btnResetActionPerformed(null);
            loadtickettable();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid number format in Ticket ID, Base Price, or category fields.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database operation failed:\n" + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (txtTicketID.getText().trim().isEmpty() || txtTicketID.isEnabled()) {
            JOptionPane.showMessageDialog(this, "Please select an existing record from the table to delete.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete Ticket ID: " + txtTicketID.getText() + "?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            int ticketId = Integer.parseInt(txtTicketID.getText().trim());
            String sql = "DELETE FROM ticket WHERE ticketId = ?";
            try (Connection conn = DatabaseConnection.connect();
                 PreparedStatement pst = conn.prepareStatement(sql)) {
                pst.setInt(1, ticketId);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Ticket deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                btnResetActionPerformed(null);
                loadtickettable();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Failed to delete ticket:\n" + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        }   
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TicketForm("username").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkParking;
    private javax.swing.JComboBox<String> cmbTicketType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAttendeeName;
    private javax.swing.JLabel lblBackstagePassFee;
    private javax.swing.JLabel lblBasePrice;
    private javax.swing.JLabel lblEventName;
    private javax.swing.JLabel lblFinalPrice;
    private javax.swing.JLabel lblHowEarly;
    private javax.swing.JLabel lblHowEarly1;
    private javax.swing.JLabel lblTicketRegistration;
    private javax.swing.JLabel lblTicketType;
    private javax.swing.JLabel lblTikcketID;
    private javax.swing.JTable tblTicketList;
    private javax.swing.JTextField txtAttendeeName;
    private javax.swing.JTextField txtBackstagePassFee;
    private javax.swing.JTextField txtBasePrice;
    private javax.swing.JTextField txtEventName;
    private javax.swing.JTextField txtHowEarly;
    private javax.swing.JTextField txtTicketID;
    // End of variables declaration//GEN-END:variables
}
